# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glos', '0002_auto_20170501_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='termbase',
            name='description',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AlterField(
            model_name='term',
            name='entry',
            field=models.CharField(max_length=60),
        ),
    ]
