# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-14 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glos', '0002_term_lclid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='lclid',
        ),
    ]
