# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-16 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glos', '0003_remove_term_lclid'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='entry',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
