# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glos', '0003_auto_20170526_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='entry',
            field=models.CharField(db_index=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='termbase',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
