# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glos', '0004_auto_20170613_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='value',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='termbase',
            old_name='termbase_name',
            new_name='name',
        ),
    ]
