# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-18 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glos', '0004_description_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='entry',
            field=models.CharField(db_index=True, default=b'', max_length=200),
        ),
    ]
