# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-30 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glos', '0005_auto_20171018_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hit', models.CharField(max_length=5, unique=True)),
            ],
        ),
    ]
