# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-06 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glos', '0006_hits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='description',
            name='entry',
            field=models.CharField(db_index=True, default='', max_length=200),
        ),
    ]
