BBBB BBBB BBBBBBXXXXXXXXX XXXXX
BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB
XXXXX XXXXXXFFFFFFFFFFFFFFFX BB BBBBBBBBBBBBBXXXXXXXXXBBBBBX
XXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
XXXXXXXBBBBB BBBBBBBBBBBBBXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBX XX
XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
XXXXXXX XX XX XXX
      XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXX
      XXXXXXXXXXXX X
        XXXXXXXXXXX XX
      X
    XXXXXXXX
BBBBB BBBBBBBBBBBBBBBBBB
BB BBBBBBBBBBBBBXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXBBBBB
BBBBB BBBBBBBBBBBBBBBBB
BBBBB BBBBBBBBBXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXBBBBBBBB
XXXXXXX
BBBB BBBB

XXXXX XXXXXXXBB BBBBBBBBXXXXX BBBBBBBBBB BBBBBBBBBBBBBBBBBX
  XXXXXXXXXXXXXXXXXXXXXXXBBB BBBXX

XXXX XXXXXXXXX XXX
XXXX XXXXXXXXXXXXXXX

    BB BBB BBBBBBBB
    XXXX XXXXXX XXX
    XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXX
        BBBBB BBBBBBBBBBBBBBBB
        XXXXXX
        BBBBB BBBBBBBBB
        BB BBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXXXX
            BBBBB BBBBBBBBBBB
                 gettext(u'Welcome,') 
                XXXXXXXXBBBBBBB BBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBXXXXXXXXXX
            BBBBBBBB
            BBBBB BBBBBBBBB
                BB BBBBBBBB
                    XX XXXXXXXX gettext(u'View site') XXXX X
                BBBBB
                BB BBBBBBBBBBBBBB BBB BBBBBBBBBBBBB
                    BBB BBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBB
                    BB BBBBBBBB
                        XX XXXXXXXX gettext(u'Documentation') XXXX X
                    BBBBB
                BBBBB
                BB BBBBBBBBBBBBBBBBBBBBBBBB
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'Change password') XXXX X
                BBBBB
                XX XXXXXXBBB BBBBBBBBBBBBBBXX gettext(u'Log out') XXXX
            BBBBBBBB
        XXXXXX
        BBBBB
        BBBBBBBB
        BBBBB BBBBBBBBBBBBBBBBBB
    XXXXXX
    XXXX XXX XXXXXX XXX
    BBBBB BBBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBXX gettext(u'Home') XXXX
    BB BBBBB XXXXXXXX BBBBB
    XXXXXX
    BBBBBBBB
    BBBBB

    BBBBB BBBBBBBB
        BB BBBBBBBB
        XXX XXXXXXXXXXXXXXXXXXXXBBB BBBBBBB BB BBBBBBBB
          XXXBB BBBBBBBBBBBB XXXXXXXXBBBBBXFFFFFFFFXXXXX
        BBBBBBXXXXX
        BBBBB
    BBBBBBBB BBBBBBBB

    XXXX XXXXXXX XXX
    XXXX XXXXXXXXXXXX XXXXXXXBBBBB BBBBBBBXXXXBBBBBBBBXX
        BBBBB BBBBBBBBBBBBBBBB
        BBBBB BBBBBBBBBBBBBBB BBBBBXXXXXXXXXBBBBBBBBBBBBB
        BBBBB BBBBBBB
        BBBBB BBBBBBBBBBBBBBBBBBBB
        
        BBBBBBBB
        BBBBB BBBBBBBBBBBBBBB
        XXX XXXXXXXXXXXXX XX
    XXXXXX
    XXXX XXX XXXXXXX XXX

    BBBBB BBBBBBXXXX XXXXXXXXXXXXXXXXXXBBBBBBBB
XXXXXX
XXXX XXX XXXXXXXXX XXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    BBBBB BBBBBBBBBB
    BBBBBBBB
XXXXXXX
XXXXXXX
